name: gromacs-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - gromacs=2023.1=nompi*
  - matplotlib
  - nglview
  - mdtraj
  - notebook
  - numpy
  - requests
  - pandas
  - seaborn
  - compilers
  - openmpi
  - cmake
  - MDAnalysis
  - matplotlib
